name: tox on main
on:
  push:
    branches:
      - 'main'
jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: sudo apt-get install ripgrep -y
      - run: pip install tox
      - run: tox

